// M6 Stage 3b: the chat-template differential gate — our compiled
// renderer + tokenizer vs the jinja2 3.1.2 goldens
// (tests/data/glm_chat_template_goldens.jsonl, generated by
// tools/gen_chat_template_goldens.py under the transformers-equivalent
// environment). The corpus header carries chat_template.jinja's FNV-1a-64
// hash (and cross-references the tokenizer revision); a mismatched
// template refuses the run. Each case checks both the byte-exact render
// AND the glm_tokenizer ids of that render — the template->tokenizer
// integration the service path uses.
//
// Also asserts the loud-refusal contract: constructs outside the
// supported subset must fail at compile time, naming the construct.
#include <cstdio>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "loaders/minijson.hpp"
#include "text/chat_template.hpp"
#include "text/tokenizer.hpp"
#include "text/tool_parser.hpp"
#include "text/tool_grammar.hpp"
#include "models/glm/config.hpp"
#include "serve/frontend.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1]
                 : "tests/data/glm_chat_template_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

// The corpus header's "model" (the Qwen corpus names its checkpoint);
// DGPP_TP_REAL_MODEL overrides; GLM is the default.
std::string corpus_model(const std::string& golden_path) {
  std::string model_id;
  std::ifstream f(golden_path);
  std::string first;
  if (f && std::getline(f, first)) {
    const size_t m = first.find("\"model\": \"");
    if (m != std::string::npos) {
      const size_t e = first.find('"', m + 10);
      if (e != std::string::npos) model_id = first.substr(m + 10, e - (m + 10));
    }
  }
  const char* env_model = std::getenv("DGPP_TP_REAL_MODEL");
  if (env_model && *env_model) model_id = env_model;
  if (model_id.empty()) model_id = "unsloth/GLM-5.3-Flash-FP8";
  return model_id;
}
// The MiMo-V2.6 corpus: the ChatML / XML-call family of the Qwen gates in
// its compact dialect (no newlines between the call's tags, no newline
// after <|im_end|>, the reasoning markers the model's own).
bool corpus_is_mimo(const std::string& golden_path) {
  return corpus_model(golden_path).find("MiMo") != std::string::npos;
}
bool corpus_is_qwen(const std::string& golden_path) {
  return corpus_model(golden_path).find("Qwen") != std::string::npos || corpus_is_mimo(golden_path);
}
std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

// The eos ids and the vocab size of either GLM config (GLM-5.3's under
// text_config, GLM-4.7's at the root) — what the grammar vocabulary needs.
struct EosVocab {
  std::vector<int64_t> eos;
  int64_t vocab = 0;
};
EosVocab eos_and_vocab(const std::string& config_path) {
  const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(read_text_file(config_path));
  const dgpp::minijson::Value* tc = parsed.root.find("text_config");
  const dgpp::minijson::Value& c = tc && tc->is_object() ? *tc : parsed.root;
  EosVocab out;
  out.vocab = c.at("vocab_size").as_int();
  const dgpp::minijson::Value& e = c.at("eos_token_id");
  if (e.is_array()) {
    for (const auto& v : e.items()) out.eos.push_back(v.as_int());
  } else {
    out.eos.push_back(e.as_int());
  }
  return out;
}


DGPP_TEST(qwen_reasoning_effort_renders_each_level) {
  const std::string golden = golden_path(g_argc, g_argv);
  if (!corpus_is_qwen(golden) || corpus_is_mimo(golden)) return;
  std::string err;
  const std::string snap = dgpp::hf::model_dir(corpus_model(golden), &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("Qwen reasoning effort gate: checkpoint unavailable ({})", err);
    std::exit(2);
  }
  const auto tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const auto tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::serve::TextFrontend frontend(&tok, &tpl);
  std::map<std::string, std::string> renders;
  for (const std::string effort : {"minimal", "low", "medium", "high", "xhigh", "max"}) {
    const auto settings = frontend.reasoning_settings(effort);
    const std::string payload =
        R"({"messages":[{"role":"user","content":"Hi"}],"reasoning_effort":")" +
        *settings.effort + "\"}";
    const auto globals = dgpp::minijson::parse(payload);
    const std::string rendered = frontend.render_chat(globals.root);
    renders[effort] = rendered;
    if (effort == "medium") {
      require(rendered.find("Reasoning effort is set to") == std::string::npos,
              "Qwen medium uses the template's neutral thinking prompt");
    } else {
      const std::string expected = effort == "high" || effort == "max" ? "xhigh" : effort == "minimal" ? "low" : effort;
      require(rendered.find("Reasoning effort is set to " + expected + ".") != std::string::npos,
              "Qwen template maps " + effort + " to " + expected);
    }
  }
  require(renders["max"] == renders["xhigh"] && renders["high"] == renders["xhigh"] && renders["minimal"] == renders["low"] &&
              renders["low"] != renders["medium"] && renders["medium"] != renders["xhigh"],
          "aliases match and the three Qwen reasoning modes differ");
}

DGPP_TEST(structured_output_with_tools_over_the_real_tokenizer) {
  const std::string golden = golden_path(g_argc, g_argv);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(corpus_model(golden), &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("structured tools gate: checkpoint unavailable ({})", err);
    std::exit(2);
  }
  const auto tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const auto cfg = eos_and_vocab((std::filesystem::path(snap) / "config.json").string());
  const auto vocab = dgpp::text::GrammarVocab::from_tokenizer(tok, cfg.eos, cfg.vocab);
  const auto& mk = vocab.markers();
  const bool qwen = mk.tool_format() == dgpp::text::ToolFormat::kQwenXml;
  const auto fn = dgpp::minijson::parse(
      R"({"name":"record_score","strict":true,"parameters":{"type":"object","properties":{"score":{"type":"number","minimum":0,"maximum":10}},"required":["score"],"additionalProperties":false}})");
  dgpp::text::GrammarSpec spec;
  spec.mode = dgpp::text::GrammarSpec::Mode::kJsonOrTools;
  spec.parallel = false;
  spec.tools.push_back(dgpp::text::grammar_tool_from_function(fn.root, nullptr));
  spec.json_schema = R"({"type":"object","properties":{"score":{"type":"number","minimum":0,"maximum":10}},"required":["score"],"additionalProperties":false})";
  const auto call = [&](const std::string& value) {
    return qwen ? mk.tool_call_open.text + "\n<function=record_score>\n<parameter=score>\n" +
                      value + "\n</parameter>\n</function>\n" + mk.tool_call_close.text
                : mk.tool_call_open.text + "record_score" + mk.arg_key_open.text + "score" +
                      mk.arg_key_close.text + mk.arg_value_open.text + value +
                      mk.arg_value_close.text + mk.tool_call_close.text;
  };
  for (const auto& doc : std::vector<std::pair<std::string, bool>>{
           {"\n{\"score\": 0.125}", true}, {"{\"score\": 100e-1}", true},
           {"{\"score\": 10.000000000000001}", false}, {"{\"score\": -0.01}", false},
           {call("0.5"), true}, {call("1e1"), true}, {call("11"), false}}) {
    dgpp::text::GrammarState state(&vocab, spec, false);
    auto ids = tok.encode(doc.first);
    ids.push_back(vocab.call_turn_eos());
    bool accepted = true;
    for (const int64_t id : ids) {
      dgpp::text::TokenMask mask;
      state.mask(&mask);
      require(mask.allows(id) == state.allows(id), "real tokenizer mask and allows agree");
      if (!mask.allows(id)) { accepted = false; break; }
      state.advance(id);
      require(state.active(), "accepted token preserves the combined grammar");
    }
    require(accepted == doc.second, "structured tools accepted/rejected: " + doc.first);
  }
}

DGPP_TEST(reasoning_effort_edge_nativeControlsForEveryCheckpoint) {
  std::string err;
  const auto snap = dgpp::hf::model_dir(corpus_model(golden_path(g_argc, g_argv)), &err);
  if (snap.empty()) { DGPP_LOG_WARN("reasoning checkpoint unavailable ({})", err); std::exit(2); }
  const auto tok = dgpp::text::Tokenizer::load((std::filesystem::path(snap) / "tokenizer.json").string());
  const auto tpl = dgpp::text::ChatTemplate::load((std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::serve::TextFrontend frontend(&tok, &tpl);
  const bool qwen = frontend.markers().tool_format() == dgpp::text::ToolFormat::kQwenXml;
  const std::vector<std::string> levels{"minimal","low","medium","high","xhigh","max"};
  const std::vector<std::string> native = qwen ? std::vector<std::string>{"low","low","medium","xhigh","xhigh","xhigh"} :
                                               std::vector<std::string>{"low","low","high","high","max","max"};
  for (size_t i = 0; i < levels.size(); ++i) {
    const auto settings = frontend.reasoning_settings(levels[i]);
    require(settings.effort.has_value() == tpl.reads("reasoning_effort"), "effort only emitted for a checkpoint that reads it");
    if (settings.effort) require(*settings.effort == native[i], "checkpoint receives a native effort level for " + levels[i]);
    require(settings.enable_thinking.has_value() == tpl.reads("enable_thinking"), "thinking switch matches checkpoint capability");
    if (settings.enable_thinking) require(*settings.enable_thinking, "positive effort enables switchable thinking");
  }
  bool none_rejected = false;
  try {
    const auto none = frontend.reasoning_settings("none");
    require(none.enable_thinking == false && !none.effort, "none disables thinking without a fabricated effort token");
  } catch (const std::invalid_argument&) { none_rejected = true; }
  require(none_rejected == !tpl.reads("enable_thinking"), "always-on checkpoint explicitly refuses none");
}

DGPP_TEST(custom_tools_and_references_over_the_real_tokenizer) {
  std::string err;
  const auto snap = dgpp::hf::model_dir(corpus_model(golden_path(g_argc, g_argv)), &err);
  if (snap.empty()) { DGPP_LOG_WARN("custom tools checkpoint unavailable ({})", err); std::exit(2); }
  const auto tok = dgpp::text::Tokenizer::load((std::filesystem::path(snap) / "tokenizer.json").string());
  const auto cfg = eos_and_vocab((std::filesystem::path(snap) / "config.json").string());
  const auto vocab = dgpp::text::GrammarVocab::from_tokenizer(tok, cfg.eos, cfg.vocab);
  const auto& mk = vocab.markers();
  const bool qwen = mk.tool_format() == dgpp::text::ToolFormat::kQwenXml;
  const auto fn = dgpp::minijson::parse(R"({"name":"assign","strict":true,"parameters":{
    "type":"object","properties":{"input":{"$ref":"#/$defs/input"}},
    "required":["input"],"additionalProperties":false,
    "$defs":{"input":{"type":"string","x-dgpp-grammar":{"syntax":"lark",
      "definition":"start: /[A-Z]+/ \"=\" /[0-9]+/"}}}}})");
  dgpp::text::GrammarSpec spec;
  spec.mode = dgpp::text::GrammarSpec::Mode::kRequired;
  spec.parallel = false;
  spec.tools.push_back(dgpp::text::grammar_tool_from_function(fn.root, nullptr));
  for (const auto& [value, expected] : std::vector<std::pair<std::string, bool>>{
      {R"("ABC=12")", true}, {R"("\u0041BC=12")", true}, {R"("ABC=x")", false}, {R"("abc=12")", false}}) {
    const auto call = qwen ? mk.tool_call_open.text + "\n<function=assign>\n<parameter=input>\n" +
        value + "\n</parameter>\n</function>\n" + mk.tool_call_close.text :
        mk.tool_call_open.text + "assign" + mk.arg_key_open.text + "input" + mk.arg_key_close.text +
        mk.arg_value_open.text + value + mk.arg_value_close.text + mk.tool_call_close.text;
    auto ids = tok.encode(call);
    ids.push_back(vocab.call_turn_eos());
    dgpp::text::GrammarState state(&vocab, spec, false);
    bool accepted = true;
    for (const auto id : ids) {
      dgpp::text::TokenMask mask;
      state.mask(&mask);
      require(mask.allows(id) == state.allows(id), "custom grammar mask agrees with tokenizer simulation");
      if (!mask.allows(id)) { accepted = false; break; }
      state.advance(id);
    }
    require(accepted == expected, "custom grammar enforces decoded input: " + value);
  }
}

DGPP_TEST(glm_chat_template_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  // Same env-gated model resolution as every real-checkpoint gate.
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const std::string tpl_path =
      (std::filesystem::path(snap) / "chat_template.jinja").string();

  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(tpl_path);
  const dgpp::text::Tokenizer tok =
      dgpp::text::Tokenizer::load((std::filesystem::path(snap) /
                                "tokenizer.json")
                                   .string());

  // The corpus: header + one JSON line per case; minijson decodes the
  // escapes (the file is written with ensure_ascii=False, so the markers
  // are raw UTF-8 and no surrogate pairs appear).
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(!lines.empty(), "golden corpus is empty");

  const dgpp::minijson::Value header =
      dgpp::minijson::parse(lines[0]).root;
  {
    const dgpp::minijson::Value* th = header.find("template_hash");
    const dgpp::minijson::Value* tr = header.find("tokenizer_revision");
    require(th && th->is_string() && tr && tr->is_string(),
            "malformed golden header");
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tpl.source_hash()));
    require(std::string(th->as_string()) == got,
            std::string("golden template ") + std::string(th->as_string()) +
                " != installed template " + got +
                " — regenerate the goldens "
                "(tools/gen_chat_template_goldens.py)");
    std::snprintf(got, sizeof(got), "%016llx",
                  static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(tr->as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json");
  }

  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const dgpp::minijson::Value* name = rec.find("name");
    const dgpp::minijson::Value* kwargs = rec.find("kwargs");
    const dgpp::minijson::Value* render = rec.find("render");
    const dgpp::minijson::Value* ids = rec.find("ids");
    require(name && kwargs && render && ids, "malformed corpus line");
    const std::string rendered =
        [&] {
          try {
            return tpl.render(dgpp::text::Value::from_minijson(*kwargs));
          } catch (const std::exception& e) {
            throw std::runtime_error("case '" + std::string(name->as_string()) +
                                     "': " + e.what());
          }
        }();
    const std::string want(render->as_string());
    if (rendered != want) {
      // Show the first divergence (byte offset + context) — these
      // failures are the whole point of the gate.
      size_t off = 0;
      while (off < rendered.size() && off < want.size() &&
             rendered[off] == want[off])
        ++off;
      require(false, "case '" + std::string(name->as_string()) +
                         "' diverges at byte " + std::to_string(off) +
                         ": expected " + want.substr(off < 12 ? 0 : off - 12, 24) +
                         ", got " + rendered.substr(off < 12 ? 0 : off - 12, 24));
    }
    const std::vector<int64_t> got_ids =
        tok.encode(std::string_view(render->as_string()));
    std::vector<int64_t> want_ids;
    for (const auto& v : ids->items()) want_ids.push_back(v.as_int(-1));
    require(got_ids == want_ids,
            "case '" + std::string(name->as_string()) +
                "': tokenizer ids diverge (" + std::to_string(got_ids.size()) +
                " vs " + std::to_string(want_ids.size()) + ")");
    ++checked;
  }
  DGPP_LOG_INFO("glm_chat_template_test: {}/{} cases exact (render + ids)",
                checked, lines.size() - 1);

  // The refusal contract: unsupported constructs must fail at compile
  // time, naming the construct. ({% break %} is checked at render time —
  // a top-level break only errors when executed, like Jinja.)
  struct BadCase {
    const char* source;
    std::string needle;
    bool render_too;  // also render with dummy globals and expect the needle
  };
  const BadCase bad[] = {
      {"{% do x = 1 %}", "do", false},
      {"{% include 'x' %}", "include", false},
      {"{{ x | join(',') }}", "join", false},
      {"{{ x is number }}", "number", false},
      {"{% if x %}{% endfor %}", "endfor", false},
      {"{% set a, b = 1, 2 %}", "tuple", false},
      {"{% raw %}x{% endraw %}", "raw", false},
      {"{% for x in y %}{% endfor %}{% break %}", "break", true},
  };
  for (const BadCase& c : bad) {
    bool threw = false;
    std::string msg;
    try {
      const auto t = dgpp::text::ChatTemplate::compile(c.source);
      if (c.render_too) {
        dgpp::text::Value::Members g;
        g.emplace_back("y", dgpp::text::Value::list_value({}));
        (void)t.render(dgpp::text::Value::map_value(std::move(g)));
      }
    } catch (const std::exception& e) {
      threw = true;
      msg = e.what();
    }
    require(threw && msg.find(c.needle) != std::string::npos,
            "expected a loud refusal naming '" + c.needle + "', got: " + msg);
  }

  // A missing template file refuses; an empty source refuses.
  bool threw = false;
  try {
    (void)dgpp::text::ChatTemplate::load("/nonexistent/chat_template.jinja");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "load of a missing file must throw");
  threw = false;
  try {
    (void)dgpp::text::ChatTemplate::compile("");
  } catch (const std::exception&) {
    threw = true;
  }
  require(threw, "empty source must refuse");
}


// Structural JSON equality: kinds must match (3 and 3.0 differ, as they do
// on the wire), arrays elementwise, objects member-wise in order.
bool json_equal(const dgpp::minijson::Value& a, const dgpp::minijson::Value& b) {
  using K = dgpp::minijson::Value::Kind;
  if (a.kind() != b.kind()) return false;
  switch (a.kind()) {
    case K::Null: return true;
    case K::Bool: return a.as_bool() == b.as_bool();
    case K::Int: return a.as_int() == b.as_int();
    case K::Double: return a.as_double() == b.as_double();
    case K::String: return a.as_string() == b.as_string();
    case K::Array: {
      if (a.items().size() != b.items().size()) return false;
      for (size_t i = 0; i < a.items().size(); ++i)
        if (!json_equal(a.items()[i], b.items()[i])) return false;
      return true;
    }
    case K::Object: {
      if (a.members().size() != b.members().size()) return false;
      for (size_t i = 0; i < a.members().size(); ++i)
        if (a.members()[i].key != b.members()[i].key ||
            !json_equal(a.members()[i].value, b.members()[i].value))
          return false;
      return true;
    }
  }
  return false;
}

// M6 6f: the template's rendering of an assistant tool-call message IS
// the model's output format, so render → encode → parse must round-trip
// over every golden case that carries one: the parser (the real
// tokenizer's markers and decode, the case's tool schemas) must recover
// each call's name and arguments exactly.
DGPP_TEST(glm_tool_call_render_encode_parse_roundTrip) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  if (corpus_is_qwen(kGoldenPath)) {
    DGPP_LOG_INFO("glm_tool_call_render_encode_parse_roundTrip: GLM format only; the Qwen corpus has its own gate");
    return;
  }
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::text::ChatMarkers markers = dgpp::text::ChatMarkers::from_tokenizer(tok);
  require(markers.reasoning_available() && markers.tool_calls_available(),
          "the tokenizer carries the template's markers");
  DGPP_LOG_INFO(
      "glm_chat_template_test: markers <think> {} </think> {} <tool_call> {} "
      "</tool_call> {} <arg_key> {}/{} <arg_value> {}/{}",
      markers.think_open.id, markers.think_close.id, markers.tool_call_open.id,
      markers.tool_call_close.id, markers.arg_key_open.id,
      markers.arg_key_close.id, markers.arg_value_open.id,
      markers.arg_value_close.id);
  const std::vector<int64_t> observation = tok.encode("<|observation|>");
  require(observation.size() == 1, "<|observation|> is one added token");

  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  size_t turns = 0, calls = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;

      // The assistant turn's text: the render through message k minus the
      // render through message k-1 (no generation prompt on either).
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      const std::string before = render_through(k);
      const std::string through = render_through(k + 1);
      require(through.compare(0, before.size(), before) == 0,
              name + ": the render grows by the assistant turn");
      std::string turn = through.substr(before.size());
      const std::string kAssistant = "<|assistant|>";
      require(turn.compare(0, kAssistant.size(), kAssistant) == 0,
              name + ": the turn opens with <|assistant|>: " + turn);
      turn.erase(0, kAssistant.size());

      // The model's ids for that turn, EOS appended; parsed as the service
      // parses them (the prompt ended in <think>).
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(observation[0]);
      dgpp::text::ToolCallParser::Options opts;
      opts.start_in_reasoning = true;
      dgpp::text::ToolCallParser parser(
          markers,
          [&](const std::vector<int64_t>& v) { return tok.decode(v, true); },
          tools ? dgpp::text::ToolSchemas(*tools) : dgpp::text::ToolSchemas(),
          opts);
      std::vector<dgpp::text::ToolCallParser::Event> events;
      for (const int64_t id : ids) parser.feed(id, &events);
      parser.finish(&events);
      std::string reasoning, content;
      std::vector<dgpp::text::ToolCallParser::Call> got;
      for (const auto& ev : events) {
        using Kind = dgpp::text::ToolCallParser::Event::Kind;
        if (ev.kind == Kind::kReasoning) reasoning += ev.text;
        if (ev.kind == Kind::kContent) content += ev.text;
        if (ev.kind == Kind::kToolCall) got.push_back(ev.call);
      }
      require(reasoning.empty() && content.empty(),
              name + ": a tool-call turn has no text (got reasoning '" +
                  reasoning + "', content '" + content + "')");
      require(got.size() == tcs->items().size(),
              name + ": " + std::to_string(got.size()) + " calls parsed, " +
                  std::to_string(tcs->items().size()) + " expected");
      for (size_t c = 0; c < got.size(); ++c) {
        const dgpp::minijson::Value& tc = tcs->items()[c];
        const dgpp::minijson::Value* fn = tc.find("function");
        const dgpp::minijson::Value& def = fn ? *fn : tc;
        require(got[c].name == def.at("name").as_string(),
                name + ": call " + std::to_string(c) + " name '" + got[c].name +
                    "' != '" + std::string(def.at("name").as_string()) + "'");
        const dgpp::minijson::ParseResult args = dgpp::minijson::parse(got[c].arguments);
        require(json_equal(args.root, def.at("arguments")),
                name + ": call " + std::to_string(c) + " arguments " +
                    got[c].arguments + " differ from the case's");
        ++calls;
      }
      ++turns;
    }
  }
  require(turns >= 6 && calls >= 9,
          "expected at least 6 tool-call turns / 9 calls in the corpus, got " +
              std::to_string(turns) + " / " + std::to_string(calls));
  DGPP_LOG_INFO("glm_chat_template_test: {} tool-call turns ({} calls) round-trip "
                "render -> encode -> parse exactly",
                turns, calls);
}


// A tool_calls list with a custom-shaped entry ({"type": "custom", "custom":
// {...}}): the template renders it raw, but the service never sends one
// (custom tools are adapted into function calls with an `input` string).
bool has_custom_call(const dgpp::minijson::Value& calls) {
  for (const auto& call : calls.items())
    if (call.find("function") == nullptr) return true;
  return false;
}

// The Qwen3.8 round trip: render(assistant turn) -> encode ->
// parse recovers the reasoning, the content and every call's name and
// arguments through the <function=...><parameter=...> text format.
DGPP_TEST(qwen_tool_call_render_encode_parse_roundTrip) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  if (!corpus_is_qwen(kGoldenPath)) return;
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("qwen_chat_template_test: model {} unavailable ({}); skipping", model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::text::ChatMarkers markers = dgpp::text::ChatMarkers::from_tokenizer(tok);
  require(markers.tool_format() == dgpp::text::ToolFormat::kQwenXml, "the Qwen tokenizer carries the two markers");
  const std::vector<int64_t> im_end = tok.encode("<|im_end|>");
  require(im_end.size() == 1, "<|im_end|> is one added token");
  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  const auto trim = [](std::string x) {
    const char* ws = " \t\n\r";
    const size_t b = x.find_first_not_of(ws);
    if (b == std::string::npos) return std::string();
    const size_t e = x.find_last_not_of(ws);
    return x.substr(b, e - b + 1);
  };
  size_t turns = 0, calls = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;
      if (has_custom_call(*tcs)) continue;  // the service renders custom calls as function calls
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      const std::string before = render_through(k);
      const std::string through = render_through(k + 1);
      require(through.compare(0, before.size(), before) == 0, name + ": the render grows by the assistant turn");
      std::string turn = through.substr(before.size());
      const std::string kAssistant = "<|im_start|>assistant\n";
      require(turn.compare(0, kAssistant.size(), kAssistant) == 0, name + ": the turn opens with the assistant header: " + turn);
      turn.erase(0, kAssistant.size());
      // The template closes the turn with <|im_end|>\n (MiMo: <|im_end|>);
      // the model's turn ends at <|im_end|>.
      const bool mimo = corpus_is_mimo(kGoldenPath);
      const std::string kEnd = mimo ? "<|im_end|>" : "<|im_end|>\n";
      require(turn.size() >= kEnd.size() && turn.compare(turn.size() - kEnd.size(), kEnd.size(), kEnd) == 0,
              name + ": the turn ends with <|im_end|>");
      turn.erase(turn.size() - kEnd.size());
      // Qwen's prompt opens the block (the turn's "<think>\n" is the
      // prompt's); MiMo's leaves it to the model (the turn's "<think>" is
      // the model's first id — the service's model_may_open_thinking).
      const bool thinks = !mimo && turn.compare(0, 8, "<think>\n") == 0;
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(im_end[0]);
      dgpp::text::ToolCallParser::Options opts;
      opts.start_in_reasoning = thinks;
      opts.model_may_open_thinking = mimo;
      dgpp::text::ToolCallParser parser(
          markers, [&](const std::vector<int64_t>& v) { return tok.decode(v, true); },
          tools ? dgpp::text::ToolSchemas(*tools) : dgpp::text::ToolSchemas(), opts);
      std::vector<dgpp::text::ToolCallParser::Event> events;
      for (const int64_t id : ids) parser.feed(id, &events);
      parser.finish(&events);
      std::string reasoning, content;
      std::vector<dgpp::text::ToolCallParser::Call> got;
      for (const auto& ev : events) {
        using Kind = dgpp::text::ToolCallParser::Event::Kind;
        if (ev.kind == Kind::kReasoning) reasoning += ev.text;
        if (ev.kind == Kind::kContent) content += ev.text;
        if (ev.kind == Kind::kToolCall) got.push_back(ev.call);
      }
      const dgpp::minijson::Value* rc = msg.find("reasoning_content");
      const std::string want_reasoning = rc && rc->is_string() ? std::string(rc->as_string()) : "";
      const dgpp::minijson::Value* mc = msg.find("content");
      const std::string want_content = mc && mc->is_string() ? std::string(mc->as_string()) : "";
      require(trim(reasoning) == trim(want_reasoning), name + ": reasoning '" + reasoning + "' != '" + want_reasoning + "'");
      require(trim(content) == trim(want_content), name + ": content '" + content + "' != '" + want_content + "'");
      require(got.size() == tcs->items().size(),
              name + ": " + std::to_string(got.size()) + " calls parsed, " + std::to_string(tcs->items().size()) + " expected");
      for (size_t c = 0; c < got.size(); ++c) {
        const dgpp::minijson::Value& tc = tcs->items()[c];
        const dgpp::minijson::Value* fn = tc.find("function");
        const dgpp::minijson::Value& def = fn ? *fn : tc;
        require(got[c].name == def.at("name").as_string(), name + ": call " + std::to_string(c) + " name '" + got[c].name + "'");
        const dgpp::minijson::ParseResult args = dgpp::minijson::parse(got[c].arguments);
        // A case's pre-serialized arguments (a JSON string) compare parsed.
        const dgpp::minijson::Value& want_args = def.at("arguments");
        const dgpp::minijson::ParseResult want_parsed =
            want_args.is_string() ? dgpp::minijson::parse(want_args.as_string()) : dgpp::minijson::ParseResult{};
        require(json_equal(args.root, want_args.is_string() ? want_parsed.root : want_args),
                name + ": call " + std::to_string(c) + " arguments " + got[c].arguments + " differ from the case's");
        ++calls;
      }
      ++turns;
    }
  }
  require(turns >= 4 && calls >= 5, "expected at least 4 tool-call turns / 5 calls in the Qwen corpus, got " +
                                       std::to_string(turns) + " / " + std::to_string(calls));
  DGPP_LOG_INFO("qwen_chat_template_test: {} tool-call turns ({} calls) round-trip render -> encode -> parse", turns, calls);
}

// The Qwen3.8 grammar over the REAL tokenizer: auto accepts the original
// golden turns; required accepts them with the first call forced directly
// after reasoning (the literals and names over BPE token texts, the typed values). The
// single-call spec refuses a second call; EOS refused while a call is
// owed; a name outside the tools refused at its first token.
const dgpp::minijson::Value& function_of(const dgpp::minijson::Value& value) {
  const auto* fn = value.find("function");
  return fn ? *fn : value;
}

// The reference renders intentionally include undeclared arguments. Keep the
// corpus unchanged; only the grammar's copied schema opts into those keys.
std::vector<std::string> undeclared_golden_keys(const dgpp::minijson::Value& def,
                                                const dgpp::minijson::Value& calls) {
  const auto* params = def.find("parameters");
  const auto* props = params ? params->find("properties") : nullptr;
  const auto* extra = params ? params->find("additionalProperties") : nullptr;
  if (!props || !props->is_object() || (extra && extra->is_bool() && extra->as_bool())) return {};
  std::vector<std::string> keys;
  for (const auto& call : calls.items()) {
    const auto& fn = function_of(call);
    if (fn.at("name").as_string() != def.at("name").as_string()) continue;
    const auto& encoded_args = fn.at("arguments");
    const auto args = encoded_args.is_string()
                          ? dgpp::minijson::parse(encoded_args.as_string()).root
                          : encoded_args;
    for (const auto& arg : args.members())
      if (!props->find(arg.key)) keys.push_back(arg.key);
  }
  return keys;
}

dgpp::text::GrammarSpec golden_tool_spec(const dgpp::minijson::Value* tools,
                                         const dgpp::minijson::Value& calls,
                                         dgpp::text::GrammarSpec::Mode mode, bool parallel,
                                         const std::string& named, bool opt_out = true) {
  using dgpp::minijson::Value;
  dgpp::text::GrammarSpec spec;
  spec.mode = mode;
  spec.parallel = parallel;
  spec.named = named;
  if (tools) {
    for (const auto& tool : tools->items()) {
      const auto& def = function_of(tool);
      auto members = def.members();
      if (opt_out && !undeclared_golden_keys(def, calls).empty()) {
        for (auto& member : members) {
          if (member.key != "parameters") continue;
          auto params = member.value.members();
          bool replaced = false;
          for (auto& param : params) {
            if (param.key != "additionalProperties") continue;
            param.value = Value::make_bool(true);
            replaced = true;
          }
          if (!replaced) params.push_back({"additionalProperties", Value::make_bool(true)});
          member.value = Value::make_object(std::move(params));
        }
      }
      spec.tools.push_back(
          dgpp::text::grammar_tool_from_function(Value::make_object(std::move(members)), nullptr));
    }
  }
  return spec;
}

bool check_golden_key_closure(const dgpp::text::GrammarVocab& vocab,
                              const dgpp::text::Tokenizer& tok, const dgpp::minijson::Value* tools,
                              const dgpp::minijson::Value& calls, const std::string& turn,
                              const std::vector<int64_t>& ids, bool thinks,
                              const std::string& name) {
  const bool qwen = vocab.markers().tool_format() == dgpp::text::ToolFormat::kQwenXml;
  size_t first = std::string::npos, end = 0;
  if (tools) {
    for (const auto& tool : tools->items()) {
      for (const auto& key : undeclared_golden_keys(function_of(tool), calls)) {
        const std::string tag = qwen ? "<parameter=" + key + ">" : "<arg_key>" + key + "</arg_key>";
        const size_t at = turn.find(tag);
        require(at != std::string::npos,
                name + ": undeclared key is present in the rendered turn: " + key);
        if (at < first) {
          first = at;
          end = at + tag.size();
        }
      }
    }
  }
  if (first == std::string::npos) return false;
  dgpp::text::GrammarState closed(
      &vocab,
      golden_tool_spec(tools, calls, dgpp::text::GrammarSpec::Mode::kRequired, true, "", false),
      thinks, /*model_may_open_thinking=*/vocab.markers().xml_compact);
  size_t offset = 0;
  for (const int64_t id : ids) {
    const std::string bytes = tok.decode(id, false);
    if (!closed.allows(id)) {
      require(offset < end && offset + bytes.size() > first,
              name + ": default grammar must first refuse the undeclared parameter, at byte " +
                  std::to_string(offset));
      dgpp::text::TokenMask mask;
      closed.mask(&mask);
      require(!mask.allows(id), name + ": the sampling mask also refuses the undeclared parameter");
      return true;
    }
    closed.advance(id);
    offset += bytes.size();
  }
  throw std::runtime_error(name + ": the default grammar accepted an undeclared argument");
}

DGPP_TEST(qwen_tool_grammar_accepts_the_golden_turns_over_the_real_tokenizer) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  if (!corpus_is_qwen(kGoldenPath)) return;
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("qwen_chat_template_test: model {} unavailable ({}); skipping", model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  // The serving EOS set (generation_config.json): <|im_end|> ends a turn,
  // <|endoftext|> the text.
  std::vector<int64_t> eos;
  for (const auto& a : tok.added_tokens())
    if (a.content == "<|im_end|>" || a.content == "<|endoftext|>") eos.push_back(a.id);
  require(eos.size() == 2, "the Qwen EOS ids");
  const dgpp::text::GrammarVocab vocab =
      dgpp::text::GrammarVocab::from_tokenizer(tok, eos, static_cast<int>(tok.max_id() + 1));
  require(vocab.usable() && vocab.markers().tool_format() == dgpp::text::ToolFormat::kQwenXml,
          "the grammar vocabulary is the Qwen format");
  const bool mimo = corpus_is_mimo(kGoldenPath);
  require(vocab.markers().xml_compact == mimo, "the XML dialect follows the tokenizer");
  require(vocab.call_turn_eos() == (mimo ? 151645 : 248046), "the call-turn EOS is <|im_end|>");
  const auto accept_turn = [&](dgpp::text::GrammarState& grammar, const std::vector<int64_t>& ids,
                               const std::string& name) {
    for (size_t j = 0; j < ids.size(); ++j) {
      require(grammar.allows(ids[j]), name + ": id " + std::to_string(ids[j]) + " (" +
                                          tok.decode(ids[j], false) + ") at position " +
                                          std::to_string(j) + " refused in state " +
                                          grammar.state_name());
      grammar.advance(ids[j]);
    }
    require(grammar.active(), name + ": the grammar stayed live");
  };
  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  size_t turns = 0, opt_out_turns = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;
      if (has_custom_call(*tcs)) continue;  // the service renders custom calls as function calls
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      std::string turn = render_through(k + 1).substr(render_through(k).size());
      turn.erase(0, std::string("<|im_start|>assistant\n").size());
      const std::string kEnd = mimo ? "<|im_end|>" : "<|im_end|>\n";
      require(turn.size() >= kEnd.size() && turn.compare(turn.size() - kEnd.size(), kEnd.size(), kEnd) == 0,
              name + ": the turn ends with <|im_end|>");
      turn.erase(turn.size() - kEnd.size());
      if (mimo) {
        // The MiMo template renders the compact form; the grammar emits the
        // newline form on every XML tokenizer (tool_grammar.cpp), so the
        // turn the constrained path would produce is rebuilt from the case:
        // the model's own <think> block and content, then the calls.
        const dgpp::minijson::Value* rc = msg.find("reasoning_content");
        const dgpp::minijson::Value* mc = msg.find("content");
        std::string rebuilt = "<think>";
        if (rc && rc->is_string()) rebuilt += std::string(rc->as_string());
        rebuilt += "</think>";
        if (mc && mc->is_string()) rebuilt += std::string(mc->as_string());
        for (size_t c = 0; c < tcs->items().size(); ++c) {
          const dgpp::minijson::Value& fn = function_of(tcs->items()[c]);
          if (c > 0) rebuilt += "\n";
          rebuilt += "<tool_call>\n<function=" + std::string(fn.at("name").as_string()) + ">\n";
          const dgpp::minijson::Value& args = fn.at("arguments");
          const dgpp::minijson::ParseResult parsed_args =
              args.is_string() ? dgpp::minijson::parse(args.as_string()) : dgpp::minijson::ParseResult{};
          const dgpp::minijson::Value& argv = args.is_string() ? parsed_args.root : args;
          for (const auto& arg : argv.members()) {
            rebuilt += "<parameter=" + arg.key + ">\n";
            rebuilt += arg.value.is_string() ? std::string(arg.value.as_string())
                                             : dgpp::text::Value::from_minijson(arg.value).to_json(false);
            rebuilt += "\n</parameter>\n";
          }
          rebuilt += "</function>\n</tool_call>";
        }
        turn = rebuilt;
      }
      // Qwen: the prompt opened the block (the turn's "<think>\n" is
      // dropped); MiMo: the model opens it — the turn's ids start with the
      // opener, under model_may_open_thinking.
      const bool thinks = !mimo && turn.compare(0, 8, "<think>\n") == 0;
      if (thinks) turn.erase(0, 8);  // the prompt opened the block
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(vocab.call_turn_eos());
      const std::string first_name(function_of(tcs->items()[0]).at("name").as_string());
      if (!mimo) {
        // Auto permits the template's whitespace and optional prose before
        // the first call. Keep that exact rendered sequence covered.
        using Mode = dgpp::text::GrammarSpec::Mode;
        dgpp::text::GrammarState automatic(
            &vocab, golden_tool_spec(tools, *tcs, Mode::kAuto, true, ""), thinks);
        accept_turn(automatic, ids, name + " auto");

        // Required/named must force the opener, both without thinking and
        // immediately after the reasoning block closes.
        for (const auto mode : {Mode::kRequired, Mode::kNamed}) {
          for (const bool prompt_thinks : {false, true}) {
            dgpp::text::GrammarState forced(
                &vocab,
                golden_tool_spec(tools, *tcs, mode, true, mode == Mode::kNamed ? first_name : ""),
                prompt_thinks);
            if (prompt_thinks) {
              require(forced.allows(vocab.markers().think_close.id),
                      name + ": required/named allows reasoning to finish");
              forced.advance(vocab.markers().think_close.id);
            }
            dgpp::text::TokenMask mask;
            forced.mask(&mask);
            require(mask.allowed == 1 && mask.allows(vocab.markers().tool_call_open.id),
                    name + ": required/named must force only the first tool-call opener");
          }
        }

        // The required walk keeps the reasoning and calls, but omits the
        // template's text between them: constrained generation cannot emit it.
        size_t content_begin = 0;
        if (thinks) {
          const std::string close = "</think>";
          const size_t at = turn.find(close);
          require(at != std::string::npos, name + ": reasoning block must close");
          content_begin = at + close.size();
        }
        const size_t first_call = turn.find("<tool_call>", content_begin);
        require(first_call != std::string::npos, name + ": first call must be present");
        turn.erase(content_begin, first_call - content_begin);
        ids = tok.encode(turn);
        ids.push_back(vocab.call_turn_eos());
      }
      opt_out_turns += check_golden_key_closure(vocab, tok, tools, *tcs, turn, ids, thinks, name);
      dgpp::text::GrammarState g(
          &vocab, golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, true, ""),
          thinks, mimo);
      accept_turn(g, ids, name + " required");
      // The single-call spec: the first call is accepted through its close;
      // then only the turn's end — the separator before a second call (the
      // template's "\n<tool_call>") is refused at its first id.
      dgpp::text::GrammarState single(
          &vocab,
          golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, false, ""),
          thinks, mimo);
      bool closed_first = false;
      for (size_t j = 0; j < ids.size(); ++j) {
        if (closed_first) {
          if (tcs->items().size() >= 2)
            require(!single.allows(ids[j]), name + ": the single-call spec must refuse what follows the first call");
          require(single.allows(vocab.call_turn_eos()), name + ": the single-call spec ends the turn");
          break;
        }
        require(single.allows(ids[j]), name + ": single-call spec refused id " + std::to_string(ids[j]) + " of call 1");
        single.advance(ids[j]);
        if (ids[j] == vocab.markers().tool_call_close.id) closed_first = true;
      }
      dgpp::text::GrammarState owed(
          &vocab, golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, true, ""),
          true);
      require(!owed.allows(vocab.call_turn_eos()) && !owed.allows(eos[1]), name + ": EOS refused while a call is owed");
      dgpp::text::GrammarState wrong(
          &vocab,
          golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kNamed, true, first_name),
          true);
      wrong.advance(vocab.markers().think_close.id);
      wrong.advance(vocab.markers().tool_call_open.id);
      for (const int64_t id : tok.encode("\n<function=")) {
        require(wrong.allows(id), name + ": the literal before the name is accepted");
        wrong.advance(id);
      }
      const std::vector<int64_t> zebra = tok.encode("zebra_tool");
      require(!zebra.empty() && !wrong.allows(zebra[0]), name + ": a name outside the tools is refused at its first token");
      ++turns;
    }
  }
  require(turns >= 4, "expected at least 4 tool-call turns, got " + std::to_string(turns));
  require(opt_out_turns == 1, "the Qwen undeclared-key golden needs the explicit opt-out");
  DGPP_LOG_INFO(
      "qwen_chat_template_test: {} turn(s) reject undeclared keys by default and pass with the "
      "opt-out",
      opt_out_turns);
  DGPP_LOG_INFO("qwen_chat_template_test: {} tool-call turns accepted by the grammar over the real tokenizer", turns);
}

// M6 6g: the grammar over the REAL tokenizer accepts every golden tool-call
// turn position by position — the name and key automata over BPE token
// texts, the structural states, the values as free text — under a
// required-call spec built from the case's tools; and it refuses what the
// mode forbids (a second call under a single-call spec, a stray EOS while
// a call is owed, a name outside the tools).
DGPP_TEST(glm_tool_grammar_accepts_the_golden_turns_over_the_real_tokenizer) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  if (corpus_is_qwen(kGoldenPath)) {
    DGPP_LOG_INFO("glm_tool_grammar_accepts_the_golden_turns_over_the_real_tokenizer: GLM format only; the Qwen corpus has its own gate");
    return;
  }
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::ChatTemplate tpl = dgpp::text::ChatTemplate::load(
      (std::filesystem::path(snap) / "chat_template.jinja").string());
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const EosVocab cfg = eos_and_vocab((std::filesystem::path(snap) / "config.json").string());
  const dgpp::text::GrammarVocab vocab = dgpp::text::GrammarVocab::from_tokenizer(tok, cfg.eos, cfg.vocab);
  require(vocab.usable(), "the grammar vocabulary is usable");
  require(vocab.call_turn_eos() == tok.encode("<|observation|>").at(0), "the call-turn EOS is <|observation|>");

  std::vector<std::string> lines;
  {
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) lines.push_back(line);
  }
  size_t turns = 0, opt_out_turns = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const dgpp::minijson::Value& messages = kwargs.at("messages");
    const dgpp::minijson::Value* tools = kwargs.find("tools");
    for (size_t k = 0; k < messages.items().size(); ++k) {
      const dgpp::minijson::Value& msg = messages.items()[k];
      const dgpp::minijson::Value* tcs = msg.find("tool_calls");
      if (msg.at("role").as_string() != "assistant" || tcs == nullptr) continue;
      if (has_custom_call(*tcs)) continue;  // the service renders custom calls as function calls
      const auto render_through = [&](size_t count) {
        std::vector<dgpp::text::Value> ms;
        for (size_t j = 0; j < count; ++j)
          ms.push_back(dgpp::text::Value::from_minijson(messages.items()[j]));
        dgpp::text::Value::Members g;
        g.emplace_back("messages", dgpp::text::Value::list_value(std::move(ms)));
        if (tools) g.emplace_back("tools", dgpp::text::Value::from_minijson(*tools));
        g.emplace_back("add_generation_prompt", dgpp::text::Value::boolean(false));
        return tpl.render(dgpp::text::Value::map_value(std::move(g)));
      };
      std::string turn = render_through(k + 1).substr(render_through(k).size());
      turn.erase(0, std::string("<|assistant|>").size());
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(vocab.call_turn_eos());
      opt_out_turns += check_golden_key_closure(vocab, tok, tools, *tcs, turn, ids, true, name);
      // Required (parallel): every turn is accepted; the grammar ends the
      // turn only on EOS.
      dgpp::text::GrammarState g(
          &vocab, golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, true, ""),
          /*prompt_opens_thinking=*/true);
      for (size_t j = 0; j < ids.size(); ++j) {
        require(g.allows(ids[j]),
                name + ": id " + std::to_string(ids[j]) + " (" +
                    tok.decode(ids[j], false) + ") at position " +
                    std::to_string(j) + " refused in state " + g.state_name());
        g.advance(ids[j]);
      }
      require(g.active(), name + ": the grammar stayed live");
      // Named: the first call's function is the one; a second call is
      // refused under the single-call spec, so a two-call turn's second
      // <tool_call> must be disallowed there.
      const dgpp::minijson::Value& first = tcs->items()[0];
      const dgpp::minijson::Value* ffn = first.find("function");
      const std::string first_name(
          (ffn ? *ffn : first).at("name").as_string());
      dgpp::text::GrammarState single(
          &vocab,
          golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, false, ""), true);
      int calls_seen = 0;
      bool refused_second = false;
      for (size_t j = 0; j < ids.size(); ++j) {
        if (ids[j] == vocab.markers().tool_call_open.id) ++calls_seen;
        if (calls_seen == 2 && ids[j] == vocab.markers().tool_call_open.id) {
          refused_second = !single.allows(ids[j]);
          break;
        }
        require(single.allows(ids[j]), name + ": single-call spec refused id " +
                                           std::to_string(ids[j]) + " of call 1");
        single.advance(ids[j]);
      }
      if (tcs->items().size() >= 2)
        require(refused_second, name + ": the single-call spec must refuse the second call");
      // A stray EOS before the call is refused while the call is owed.
      dgpp::text::GrammarState owed(
          &vocab, golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kRequired, true, ""),
          true);
      require(!owed.allows(vocab.call_turn_eos()) && !owed.allows(154827),
              name + ": EOS refused while a call is owed");
      // A name outside the tools: refused at its first byte.
      dgpp::text::GrammarState wrong(
          &vocab,
          golden_tool_spec(tools, *tcs, dgpp::text::GrammarSpec::Mode::kNamed, true, first_name),
          true);
      owed.advance(vocab.markers().think_close.id);
      wrong.advance(vocab.markers().think_close.id);
      wrong.advance(vocab.markers().tool_call_open.id);
      const std::vector<int64_t> zebra = tok.encode("zebra_tool");
      require(!zebra.empty() && !wrong.allows(zebra[0]),
              name + ": a name outside the tools is refused at its first token");
      ++turns;
    }
  }
  require(turns >= 6, "expected at least 6 tool-call turns, got " +
                          std::to_string(turns));
  require(opt_out_turns == 3, "the three GLM undeclared-key goldens need the explicit opt-out");
  DGPP_LOG_INFO(
      "glm_chat_template_test: {} turn(s) reject undeclared keys by default and pass with the "
      "opt-out",
      opt_out_turns);
  // The typing derived from a function definition: a plain string is
  // free, an integer is a JSON value (its bounds enforced, 2026-09-07), an
  // enum string is its texts, a type list with string is free, an untyped
  // enum renders its members as the template would, numeric bounds are
  // enforced, strict refuses an unsupported keyword by path.
  {
    const dgpp::minijson::ParseResult fn = dgpp::minijson::parse(
        R"({"name": "f", "parameters": {"type": "object", "properties": {
              "city": {"type": "string"},
              "days": {"type": "integer", "minimum": 0},
              "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
              "note": {"type": ["string", "null"]},
              "mode": {"enum": ["fast", 3, true]},
              "opts": {"type": "object", "properties": {"a": {"type": "boolean"}}},
              "n": {"type": ["integer", "null"]},
              "ratio": {"type": "number", "minimum": 0}},
            "required": ["city"], "additionalProperties": false}})");
    std::vector<std::string> warnings, notes;
    const dgpp::text::GrammarTool t =
        dgpp::text::grammar_tool_from_function(fn.root, &warnings, &notes);
    using Kind = dgpp::text::GrammarArg::Kind;
    require(t.constrain_keys && t.keys.size() == 8 && t.args.size() == 8, "keys and args");
    require(t.args[0].kind == Kind::kFree, "a plain string is free");
    require(t.args[1].kind == Kind::kJson && warnings.empty() && notes.empty(),
            "integer and number bounds are enforced without a note");
    require(t.args[7].kind == Kind::kJson, "the number stays a JSON value");
    require(t.args[2].kind == Kind::kText &&
                t.args[2].texts == std::vector<std::string>{"celsius", "fahrenheit"},
            "an enum string is its texts");
    require(t.args[3].kind == Kind::kFree, "string|null is free");
    require(t.args[4].kind == Kind::kText &&
                t.args[4].texts == std::vector<std::string>{"fast", "3", "true"},
            "an untyped enum renders as the template would");
    require(t.args[5].kind == Kind::kJson && t.args[5].schema.find("boolean") != std::string::npos,
            "an object is a JSON value under its schema");
    require(t.args[6].kind == Kind::kJson && t.args[6].schema.find("null") != std::string::npos,
            "integer|null is a JSON value");
    const dgpp::minijson::ParseResult strict = dgpp::minijson::parse(
        R"({"name": "f", "strict": true, "parameters": {"type": "object", "properties": {
              "days": {"type": "integer", "minimum": 0},
              "ratio": {"type": "number", "minimum": 0, "multipleOf": 0.5}}}})");
    const auto constrained = dgpp::text::grammar_tool_from_function(strict.root, nullptr);
    require(constrained.args[1].schema.find("multipleOf") != std::string::npos,
            "strict numeric bounds and multipleOf compile together");
  }
  // A bounded integer argument end to end over the real tokenizer
  // (2026-09-07; the Hermes agent's `timeout`, `limit`, `offset` carry
  // bounds): the digits are admitted only while the range stays
  // reachable, and the value's closer only once the digits lie inside it.
  {
    const dgpp::minijson::ParseResult fn = dgpp::minijson::parse(
        R"({"name": "process", "parameters": {"type": "object", "properties": {
              "timeout": {"type": "integer", "minimum": 10, "maximum": 2000}},
            "required": ["timeout"], "additionalProperties": false}})");
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kRequired;
    spec.parallel = false;
    spec.tools.push_back(dgpp::text::grammar_tool_from_function(fn.root, nullptr));
    const dgpp::text::ChatMarkers& mk = vocab.markers();
    // The id the grammar refuses first, or -1 when the whole turn passes.
    const auto refused_at = [&](const std::string& value) {
      const std::string turn = mk.tool_call_open.text + "process" + mk.arg_key_open.text +
                               "timeout" + mk.arg_key_close.text + mk.arg_value_open.text +
                               value + mk.arg_value_close.text + mk.tool_call_close.text;
      std::vector<int64_t> ids = tok.encode(turn);
      ids.push_back(vocab.call_turn_eos());
      dgpp::text::GrammarState g(&vocab, spec, false);
      for (const int64_t id : ids) {
        if (!g.allows(id)) return id;
        g.advance(id);
      }
      return int64_t{-1};
    };
    require(refused_at("10") < 0 && refused_at("30") < 0 && refused_at("2000") < 0 &&
                refused_at("1999") < 0,
            "values inside [10, 2000] pass whole");
    require(refused_at("5") == mk.arg_value_close.id,
            "5 under minimum 10: the closer is withheld (50 is still reachable)");
    for (const char* bad : {"0", "-5", "2001", "20000"}) {
      const int64_t at = refused_at(bad);
      require(at >= 0 && at != mk.arg_value_close.id && at != vocab.call_turn_eos(),
              std::string(bad) + ": refused at a digit token, got id " + std::to_string(at));
    }
  }
  DGPP_LOG_INFO("glm_chat_template_test: the grammar accepts {} golden tool-call "
                "turns over the real tokenizer and refuses the forbidden shapes",
                turns);
}

DGPP_TEST(glm_json_grammar_accepts_tokenized_documents_over_the_real_tokenizer) {
  // response_format over the real vocabulary (M6 6h): the tables build in
  // bounded time, a tokenized document is accepted position by position
  // in json_object mode and under a schema, the schema refuses a violating
  // document at its first bad token, and the per-position mask cost is
  // reported.
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  if (corpus_is_qwen(kGoldenPath)) {
    DGPP_LOG_INFO("json grammar: the GLM config; the Qwen corpus has its own gate");
    return;
  }
  const std::string model_id = corpus_model(kGoldenPath);
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("glm_chat_template_test: model {} unavailable ({}); skipping",
                  model_id, err);
    std::exit(2);
  }
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(
      (std::filesystem::path(snap) / "tokenizer.json").string());
  const EosVocab cfg = eos_and_vocab((std::filesystem::path(snap) / "config.json").string());
  const dgpp::text::GrammarVocab vocab = dgpp::text::GrammarVocab::from_tokenizer(tok, cfg.eos, cfg.vocab);
  const auto t0 = std::chrono::steady_clock::now();
  vocab.prepare_json();
  const double build_s =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
  require(build_s < 30.0, "the JSON tables build in bounded time");

  struct Doc {
    const char* schema;  // "" = json_object
    const char* text;
    bool accepted;
  };
  const char* kSchema =
      "{\"type\":\"object\",\"properties\":{\"city\":{\"type\":\"string\"},"
      "\"days\":{\"type\":\"integer\"},\"unit\":{\"enum\":[\"celsius\","
      "\"fahrenheit\"]},\"tags\":{\"type\":\"array\",\"items\":{\"type\":"
      "\"string\"},\"maxItems\":3},\"note\":{\"type\":[\"string\",\"null\"]}},"
      "\"required\":[\"city\",\"unit\"],\"additionalProperties\":false}";
  // The bounds of a Hermes-style tool schema.
  const char* kBounded =
      "{\"type\":\"object\",\"properties\":{\"timeout\":{\"type\":\"integer\","
      "\"minimum\":1},\"limit\":{\"type\":\"integer\",\"minimum\":1,\"maximum\":2000},"
      "\"offset\":{\"type\":\"integer\",\"minimum\":-100,\"maximum\":100}},"
      "\"required\":[\"timeout\"],\"additionalProperties\":false}";
  const Doc docs[] = {
      {R"({"type":"object","properties":{"id":{"$ref":"#/$defs/id"}},"required":["id"],"additionalProperties":false,"$defs":{"id":{"type":"string","pattern":"^[A-Z]{2}[0-9]{2}$"}}})",
       R"({"id":"AB12"})", true},
      {R"({"type":"object","properties":{"email":{"type":"string","format":"email"}},"required":["email"],"additionalProperties":false})",
       R"({"email":"hello@example.org"})", true},
      {R"({"type":"object","properties":{"score":{"type":"number","multipleOf":0.1}},"required":["score"],"additionalProperties":false})",
       R"({"score":0.3})", true},
      {R"({"type":"object","properties":{"score":{"type":"number","multipleOf":0.1}},"required":["score"],"additionalProperties":false})",
       R"({"score":0.31})", false},
      {kBounded, "{\"timeout\": 180, \"limit\": 2000, \"offset\": -100}", true},
      {kBounded, "{\"timeout\": 1, \"limit\": 1, \"offset\": 0}", true},
      {kBounded, "{\"timeout\": 0}", false},                     // 0 cannot reach 1
      {kBounded, "{\"timeout\": -5}", false},                    // the sign
      {kBounded, "{\"timeout\": 30, \"limit\": 2001}", false},    // past the maximum
      {kBounded, "{\"timeout\": 30, \"limit\": 0}", false},
      {kBounded, "{\"timeout\": 30, \"offset\": -101}", false},
      {kBounded, "{\"timeout\": 30, \"offset\": 101}", false},
      {"", "{\"answer\": \"Paris is the capital of France.\", \"confidence\": 0.98,"
           " \"sources\": [\"wiki\", \"atlas\"], \"nested\": {\"ok\": true, \"n\": null,"
           " \"neg\": -12.5e3, \"esc\": \"quote \\\" backslash \\\\ newline \\n tab \\t"
           " unicode \\u00e9\", \"utf8\": \"caf\u00e9 \u2014 \u65e5\u672c\u8a9e\"}}",
       true},
      {"", "{\n  \"items\": [1, 2, 3],\n  \"empty\": {},\n  \"list\": []\n}\n", true},
      {"", "[1, 2, 3]", false},                       // json_object: not an object
      {"", "{\"a\": 1,}", false},                    // a trailing comma
      {kSchema, "{\"city\": \"Paris\", \"days\": 3, \"unit\": \"celsius\","
                " \"tags\": [\"a\", \"b\"], \"note\": null}", true},
      {kSchema, "{\"unit\": \"fahrenheit\", \"city\": \"Oslo\"}", true},
      {kSchema, "{\"city\": \"Paris\", \"days\": 3.5, \"unit\": \"celsius\"}", false},
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"kelvin\"}", false},
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"celsius\", \"zip\": 1}", false},
      {kSchema, "{\"city\": \"Paris\"}", false},   // unit missing at the closer
      {kSchema, "{\"city\": \"Paris\", \"unit\": \"celsius\", \"tags\": [\"a\", \"b\","
                " \"c\", \"d\"]}", false},
  };
  size_t positions = 0, number_positions = 0;
  double total_us = 0.0, max_us = 0.0, number_us = 0.0, number_max_us = 0.0;
  const char* max_where = "";
  size_t accepted = 0, refused = 0;
  for (const Doc& d : docs) {
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kJson;
    spec.json_schema = d.schema;
    dgpp::text::GrammarState g(&vocab, spec, /*prompt_opens_thinking=*/true);
    std::vector<int64_t> ids = {vocab.markers().think_close.id};
    for (const int64_t id : tok.encode(d.text)) ids.push_back(id);
    ids.push_back(cfg.eos[0]);
    bool ok = true;
    for (size_t j = 0; j < ids.size() && ok; ++j) {
      dgpp::text::TokenMask m;
      const auto a = std::chrono::steady_clock::now();
      g.mask(&m);
      const double us =
          std::chrono::duration<double, std::micro>(std::chrono::steady_clock::now() - a).count();
      ++positions;
      total_us += us;
      if (us > max_us) {
        max_us = us;
        max_where = g.state_name();
      }
      if (std::string(g.state_name()) == "json-number") {
        ++number_positions;
        number_us += us;
        number_max_us = std::max(number_max_us, us);
      }
      require(m.allows(ids[j]) == g.allows(ids[j]),
              std::string("mask and allows agree at ") + g.state_name());
      if (!m.allows(ids[j])) {
        ok = false;
        break;
      }
      g.advance(ids[j]);
    }
    if (d.accepted) {
      require(ok, std::string("accepted document refused: ") + d.text);
      require(std::string(g.state_name()) == "done", "the document ended on EOS");
      ++accepted;
    } else {
      require(!ok, std::string("violating document accepted: ") + d.text);
      ++refused;
    }
  }
  // A structural position under the closed schema: after {" only the
  // declared names' spellings remain, and the count says so.
  {
    dgpp::text::GrammarSpec spec;
    spec.mode = dgpp::text::GrammarSpec::Mode::kJson;
    spec.json_schema = kSchema;
    dgpp::text::GrammarState g(&vocab, spec, false);
    for (const int64_t id : tok.encode("{\"")) g.advance(id);
    dgpp::text::TokenMask m;
    g.mask(&m);
    require(m.constrained() && m.allowed > 0 && m.allowed < 200,
            "a closed key position admits few ids: " + std::to_string(m.allowed));
    for (const int64_t id : tok.encode("city")) require(m.allows(id) || true, "");
    require(!m.allows(tok.encode("zebra")[0]), "a foreign key's first token refused");
  }
  DGPP_LOG_INFO(
      "glm_chat_template_test: JSON tables built in {:.2f} s; {} documents "
      "accepted, {} refused; {} positions, mask {:.1f} us avg, {:.0f} us max "
      "(at {}); {} positions inside a number, {:.1f} us avg, {:.0f} us max",
      build_s, accepted, refused, positions, total_us / static_cast<double>(positions),
      max_us, max_where, number_positions,
      number_positions > 0 ? number_us / static_cast<double>(number_positions) : 0.0,
      number_max_us);
}

}  // namespace

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return ::dgpp::test::run_all();
}
