// The DeepSeek-V4.1 prompt renderer's differential gate (plan G6): our
// Dsv41Prompt::render + tokenizer vs the goldens the checkpoint's own
// encoder produced (tests/data/dsv41_prompt_goldens.jsonl, generated by
// tools/gen_dsv41_prompt_goldens.py). Each case checks the byte-exact
// render AND the tokenizer ids of that render — the render -> tokenizer
// integration the service path uses. The corpus header cross-references
// the tokenizer revision; a different tokenizer.json refuses the run.
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/hf_cache.hpp"
#include "loaders/minijson.hpp"
#include "text/dsv41_prompt.hpp"
#include "text/tokenizer.hpp"
#include "serve/frontend.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1] : "tests/data/dsv41_prompt_goldens.jsonl";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

std::string escaped(const std::string& s, size_t limit = 400) {
  std::string out;
  for (size_t i = 0; i < s.size() && i < limit; ++i) {
    const char c = s[i];
    if (c == '\n') out += "\\n";
    else if (c == '\r') out += "\\r";
    else out += c;
  }
  if (s.size() > limit) out += "...";
  return out;
}

}  // namespace

DGPP_TEST(dsv41_prompt_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(lines.size() >= 2, "golden corpus is empty");
  const dgpp::minijson::ParseResult hp = dgpp::minijson::parse(lines[0]);
  const dgpp::minijson::Value& header = hp.root;
  std::string model_id = std::string(header.at("model").as_string());
  if (const char* env_model = std::getenv("DGPP_TP_REAL_MODEL"); env_model && *env_model) model_id = env_model;
  std::string err;
  const std::string snap = dgpp::hf::model_dir(model_id, &err);
  if (snap.empty()) {
    DGPP_LOG_WARN("dsv41_prompt_test: model {} unavailable ({}); skipping", model_id, err);
    std::exit(2);
  }
  const dgpp::text::Tokenizer tok =
      dgpp::text::Tokenizer::load((std::filesystem::path(snap) / "tokenizer.json").string());
  const dgpp::serve::Dsv41Frontend frontend(&tok);
  const std::string kHighPrefix =
      "Reasoning Effort: Absolute maximum with no shortcuts permitted.\n"
      "You MUST be very thorough in your thinking and comprehensively decompose the problem to resolve the root cause, rigorously stress-testing your logic against all potential paths, edge cases, and adversarial scenarios.\n"
      "Explicitly write out your entire deliberation process, documenting every intermediate step, considered alternative, and rejected hypothesis to ensure absolutely no assumption is left unchecked.\n\n";
  const std::string kMaxPrefix =
      "Reasoning Effort: Beyond maximum — exhaustive, relentless, and uncompromising.\n"
      "You MUST reason with the utmost depth and rigor, leaving absolutely nothing to chance: exhaustively decompose the problem into its most fundamental components, trace every causal chain to its root, and resolve the underlying cause rather than any surface symptom.\n"
      "Do not stop reasoning until you have independently verified the solution from multiple angles and are certain that no assumption remains unchecked and no error remains undiscovered.\n\n";
  for (const auto& [effort, expect] : std::vector<std::pair<std::string, std::string>>{
      {"minimal", ""}, {"low", ""}, {"medium", kHighPrefix}, {"high", kHighPrefix},
      {"xhigh", kMaxPrefix}, {"max", kMaxPrefix}}) {
    const auto settings = frontend.reasoning_settings(effort);
    const std::string payload = R"({"messages":[{"role":"user","content":"Hi"}],"reasoning_effort":")" + *settings.effort + "\"}";
    const auto globals = dgpp::minijson::parse(payload);
    const std::string rendered = frontend.render_chat(globals.root);
    const std::string_view bos = dgpp::text::Dsv41Prompt::kBos;
    if (expect.empty())
      require(rendered.find("Reasoning Effort:") == std::string::npos,
              "API low effort adds no prefix: " + effort);
    else
      require(rendered.compare(bos.size(), expect.size(), expect) == 0,
              "API effort maps to the native DeepSeek prefix: " + effort);
  }
  require(frontend.reasoning_settings("none").enable_thinking == false && !frontend.reasoning_settings("none").effort,
          "DeepSeek none uses native chat mode");
  {
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx", static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(header.at("tokenizer_revision").as_string()) == got,
            "golden tokenizer revision does not match this tokenizer.json — regenerate the goldens "
            "(tools/gen_dsv41_prompt_goldens.py)");
  }
  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const std::string want(rec.at("render").as_string());
    const std::string rendered = [&] {
      try {
        return dgpp::text::Dsv41Prompt::render(kwargs);
      } catch (const std::exception& e) {
        throw std::runtime_error("case '" + name + "': " + e.what());
      }
    }();
    if (rendered != want) {
      size_t k = 0;
      while (k < rendered.size() && k < want.size() && rendered[k] == want[k]) ++k;
      std::printf("[FAIL] case '%s' differs at byte %zu\n  got:  %s\n  want: %s\n", name.c_str(), k,
                  escaped(rendered.substr(k > 40 ? k - 40 : 0)).c_str(), escaped(want.substr(k > 40 ? k - 40 : 0)).c_str());
      require(false, "case '" + name + "': render differs from the reference encoder's");
    }
    std::vector<int64_t> want_ids;
    for (const auto& v : rec.at("ids").items()) want_ids.push_back(v.as_int());
    const std::vector<int64_t> got_ids = tok.encode(rendered);
    require(got_ids == want_ids, "case '" + name + "': the render's ids differ from the reference tokenizer's");
    ++checked;
  }
  DGPP_LOG_INFO("dsv41 prompt differential: {}/{} cases byte-exact with matching ids", checked, lines.size() - 1);
}

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return dgpp::test::run_all();
}
